version: '3.7'
services:
  app:
    build:
      context: .
      target: react_dev
    container_name: app
    command: npm start
    volumes:
      - .:/app:cached
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    tty: true
    