export const paths = {
    landing: "/",
    login: "/login",
    register: "/registro",
    tags: "/tags",
    questions: "/preguntas",
    account: "/cuenta/:username",
    roommateAccount: "/roommate/:username",
    ownerAccount: "/propietario/cuenta/:id",
    aboutUs: "/acerca",
    contacts: "/contactos",
    why: "/porque",
    houseRegister: "/registrar/inmuebles",
    publicationRegister: "/registrar/publicaciones",
    search: "/buscar",
    publicationsList: "/publicaciones",
    publicationDetail: "/publicaciones/detalle/:id",
    forgetterpass: "/recuperar",
    members: "/integrantes",
    findRoommate: "/buscar/roommate"
  };
