export const paths = {
    lading: "/",
    login: "/login",
    register: "/registro",
    account: "/micuenta",
    ownerAccount: "propietario/micuenta",
    aboutUs: "/acerca",
    contacts: "/contactos",
    why: "/porque",
    houseRegister: "/inmuebles/registrar",
    postRegister: "/publicaciones/registrar",
    search: "/buscar",
    postList: "/publicaciones",
    postDetail: "/publicaciones/detalle/:id",
    forgetterpass: "/recuperar",
    members: "/integrantes",
  };
